minimum_pre_commit_version: '2'
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: check-npm-version
        name: Check npm version
        language: system
        entry: npm --version
        pass_filenames: false
      - id: install-pnpm
        name: Install pnpm
        language: system
        entry: npm i -g pnpm@9.12.1
        pass_filenames: false
      - id: install-dependencies
        name: Install dependencies
        language: system
        entry: pnpm run deps
        pass_filenames: false
      - id: run-linter
        name: Run linter
        language: system
        entry: pnpm run lint
        pass_filenames: false
      - id: build
        name: Build
        language: system
        entry: pnpm run build
        pass_filenames: false
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]
